
let MICROS_PER_MILLI = 1000;
let MILLIS_PER_SECOND = 1000;
let SECONDS_PER_MINUTE = 60;
let MINUTES_PER_HOUR = 60;
let HOURS_PER_DAY = 24;

let MILLIS_PER_MINUTE = MILLIS_PER_SECOND * SECONDS_PER_MINUTE;
let MILLIS_PER_HOUR = MILLIS_PER_MINUTE * MINUTES_PER_HOUR;
let MILLIS_PER_DAY = MILLIS_PER_HOUR * HOURS_PER_DAY;

let SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;
let SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY;
