
var MICROS_PER_MILLI = 1000;
var MILLIS_PER_SECOND = 1000;
var SECONDS_PER_MINUTE = 60;
var MINUTES_PER_HOUR = 60;
var HOURS_PER_DAY = 24;

var MILLIS_PER_MINUTE = MILLIS_PER_SECOND * SECONDS_PER_MINUTE;
var MILLIS_PER_HOUR = MILLIS_PER_MINUTE * MINUTES_PER_HOUR;
var MILLIS_PER_DAY = MILLIS_PER_HOUR * HOURS_PER_DAY;

var SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;
var SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY;
