var g_puzzles =
[
   {
      pieces: [
         {str:["DO"], x:17, y:14},
         {str:["G","O"], x:20, y:4},
         {str:["O ","SH","E "], x:19, y:7},
         {str:["EEP","Y  "], x:18, y:2},
         {str:["I ","GO"], x:7, y:13},
         {str:["AT","T "], x:5, y:2},
         {str:["C"], x:4, y:12},
         {str:["T ","U ","RO","K "], x:2, y:2},
         {str:[" R","OS"," E"], x:19, y:11},
         {str:[" K ","TER"," N "], x:7, y:3},
         {str:["H","O"], x:2, y:13},
         {str:["DU"], x:4, y:14},
         {str:["CK","H "], x:2, y:10},
         {str:["I ","CO"], x:2, y:7},
         {str:["W"], x:17, y:12}
      ],
      grid: {
         str:[
            "       OOOO ",
            "         O  ",
            "       O O  ",
            "    O  O OOO",
            "OOO O  O O  ",
            "  O OOOOOOO ",
            "  O O  O O  ",
            "  OOOOO     ",
            "  O O O O   ",
            "      OOOO  ",
            "        O   "
         ], x:6, y:3},
      name:"THE FARM"
   },
   {
      pieces: [
         {str:["BE"], x:2, y:12},
         {str:["AT","R "], x:2, y:2},
         {str:[" I","RA"], x:17, y:5},
         {str:["  V","OPE"], x:2, y:9},
         {str:["NO"], x:2, y:7},
         {str:["CO"], x:16, y:2},
         {str:[" R"," S","TE"], x:19, y:7},
         {str:[" T","RE"," N"], x:19, y:2},
         {str:["  O","HAR"], x:18, y:13},
         {str:["M","E"], x:5, y:2},
         {str:["T","E"], x:5, y:5},
         {str:["RD"], x:19, y:11},
         {str:["IC"], x:2, y:5},
         {str:["M  ","P  ","ONY"], x:14, y:2},
         {str:["  L","CHO"], x:3, y:13},
         {str:[" D ","LYR"], x:7, y:12}
      ],
      grid: {
         str:[
            "   OOOO     ",
            "     O      ",
            "   O O      ",
            " OOOOO      ",
            "   O   O O  ",
            "   OOOOO O  ",
            "OOOO   O O  ",
            "       O O  ",
            "     OOOOOOO",
            "        O   ",
            "        O   ",
            "      OOOOO ",
            "        O   ",
            "       OOOOO"
         ], x:6, y:3},
      name: "MUSIC"
   },
   {
      pieces: [
         {str:["H","A"], x:20, y:9},
         {str:["R  ","PET"], x:2, y:7},
         {str:[" T","TR"," O"], x:19, y:5},
         {str:["UM"], x:2, y:2},
         {str:["M  ","BAG"], x:2, y:4},
         {str:[" V","PI"," O"], x:5, y:2},
         {str:["PE"], x:9, y:7},
         {str:["L ","I ","NO"], x:2, y:12},
         {str:["PIA"], x:14, y:14},
         {str:["NJO","  N"], x:18, y:2},
         {str:["BA"], x:2, y:10},
         {str:["ELE"], x:8, y:3},
         {str:["UL"], x:8, y:5},
         {str:["G ","UK","I "], x:6, y:6},
         {str:[" T"," A","DR"], x:19, y:12},
         {str:["UMS"], x:8, y:13}
      ],
      grid: {
         str:[
            "          O   ",
            "          O   ",
            "       O  O   ",
            "      OOOOOOO ",
            "       O      ",
            "       O   O  ",
            "       OOOOOOO",
            "   OOOOO   O  ",
            " O     O   O  ",
            " OOOOOOO   O  ",
            " O      OOOOO ",
            " O            ",
            " O            ",
            "OOOOO         "
         ], x:5, y:2},
      name: "INSTRUMENTS"
   },
   {
      pieces: [
         {str:["P","E"], x:5, y:2},
         {str:["A ","CH","H "], x:19, y:7},
         {str:["ER"," I"], x:19, y:2},
         {str:["AP","P "], x:16, y:2},
         {str:["  P","PLE"], x:2, y:5},
         {str:["A","R"], x:8, y:13},
         {str:["RY"], x:19, y:5},
         {str:["C ","OR","T "], x:6, y:9},
         {str:["AN"," A"], x:5, y:13},
         {str:["GE"], x:16, y:5},
         {str:["B","A"], x:20, y:11},
         {str:["GR"], x:16, y:9},
         {str:["GO"], x:16, y:7},
         {str:["N ","AP"], x:2, y:13},
         {str:["MAN","E  "], x:2, y:8},
         {str:["MON"], x:2, y:11},
         {str:["LE","O ","N "], x:2, y:2}],


      grid: { str:
      [
         "O      O     ",
         "O  OOOOO     ",
         "O  O   O     ",
         "OOOOOO O     ",
         "O  O  O      ",
         "   O  O      ",
         "   OOOOOO    ",
         "   O  O      ",
         "      O OOOOO",
         "    OOOOO    ",
         "        OOOOO",
         "        O    ",
         "        O    "
      ], x:6, y:3},
      name: "THE GOOD KIND OF SALAD"
   },
   {
      pieces: [
         {str:["PU","I "], x:17, y:2},
         {str:["N","K"], x:2, y:4},
         {str:["B ","RP","O "], x:2, y:10},
         {str:["W","N"], x:20, y:9},
         {str:["Y ","E ","LE"], x:18, y:11},
         {str:["L ","OR","W "], x:17, y:5},
         {str:[" E"," E","AN"], x:19, y:2},
         {str:["G","R"], x:5, y:2},
         {str:[" I"," T","GE"], x:4, y:11},
         {str:["W","H"], x:20, y:6},
         {str:[" R","LA"," Y"], x:7, y:11},
         {str:["CK"], x:2, y:2},
         {str:["B","L"], x:16, y:12},
         {str:[" U","RE"], x:2, y:7},
         {str:["D"], x:18, y:9}],

      grid: { str:
      [
         "    O  O O ",
         "  O O  O O ",
         "OOOOOO O O ",
         "O O O  O O ",
         "O O OOOOOO ",
         "O O O   O  ",
         "      OOOOO",
         "      O O  ",
         "      O    ",
         "     OOO   "
      ], x:6, y:3},
      name: "COLORS"
   },
   {
      pieces: [
         {str:["..W","FRA"], x:4, y:14},
         {str:["BON",".N."], x:1, y:7},
         {str:["T","S"], x:18, y:2},
         {str:["NKE","..R"], x:1, y:2},
         {str:[".P.","JEK",".R."], x:19, y:11},
         {str:["OC",".T"], x:20, y:2},
         {str:["P.","ES","P."], x:1, y:13},
         {str:["L","E"], x:21, y:5},
         {str:["TOP"], x:3, y:12},
         {str:["NST"], x:1, y:5},
         {str:[".H","MO"], x:16, y:14},
         {str:["YLL"], x:1, y:10},
         {str:["W"], x:5, y:5},
         {str:["RE"], x:20, y:15},
         {str:["H","O"], x:21, y:8},
         {str:["US","S."], x:18, y:5},
         {str:["EIN",".N."], x:5, y:2},
         {str:["D","I"], x:16, y:2},
         {str:["AU","N.","A."], x:18, y:8}],

      grid: { str:
      [
         ".....O...O..",
         ".....O...O..",
         "....OOOOOOO.",
         "..O..O...O..",
         "OOOOOOOOOOOO",
         "..O..O....O.",
         "..O.O..O..O.",
         ".OOOOO.O..O.",
         "..O.O.OOOOOO",
         "....O.....O.",
         "...OOOOOO.O.",
         "....O......."
      ], x:5, y:3},
      name: "DOCTORS"
   },
   {
      pieces: [
         {str:["TA"], x:14, y:6},
         {str:["UM",".A"], x:1, y:9},
         {str:["PE"], x:11, y:3},
         {str:["AZU"], x:12, y:13},
         {str:["FU"], x:4, y:13},
         {str:["UPE","V.."], x:19, y:10},
         {str:[".R.","BER"], x:19, y:7},
         {str:["RIW",".V."], x:1, y:6},
         {str:["O.","CH","H."], x:1, y:12},
         {str:["O.","RE","Y."], x:5, y:2},
         {str:["SIA"], x:1, y:4},
         {str:["CER",".B."], x:16, y:2},
         {str:[".O","IN",".Y"], x:20, y:2},
         {str:["KLE"], x:1, y:2},
         {str:["UL"], x:14, y:4},
         {str:[".M.","EAN"], x:17, y:13},
         {str:["G","E","N"], x:21, y:12},
         {str:["T","A"], x:18, y:5}],

      grid: { str:
      [
         "....O.........",
         "..OOOOOOO.....",
         "....O.........",
         "....O.........",
         ".OOOOO......O.",
         "..O...OOOOOOOO",
         "OOOOO..O....O.",
         "..O....O....O.",
         ".OOOOOOOOOO.O.",
         "....O..O....O.",
         "....O.......O.",
         ".OOOOO........",
         "....O........."
      ], x:4, y:3},
      name: "COLORS: THE REVENGE"
   },
   {
      pieces: [
         {str:["P","O","P"], x:2, y:7},
         {str:["S.","I.","CH"], x:2, y:11},
         {str:["L","E"], x:4, y:9},
         {str:["G","E"], x:9, y:3},
         {str:["L","A"], x:8, y:6},
         {str:["T.","OC"], x:13, y:8},
         {str:["ST",".R",".U"], x:3, y:5},
         {str:["OLA",".E."], x:5, y:13},
         {str:["F","F"], x:16, y:8},
         {str:[".M",".O","RU"], x:15, y:13},
         {str:["LOL"], x:2, y:15},
         {str:["S.","SO","E."], x:6, y:2},
         {str:["TE"], x:7, y:11},
         {str:[".K.","DEL"], x:19, y:14},
         {str:["CAN","A.."], x:17, y:4},
         {str:["RB",".R",".O"], x:20, y:10},
         {str:["LIP",".E."], x:2, y:2},
         {str:["W","N"], x:13, y:3},
         {str:["ET"], x:9, y:13},
         {str:["DY"], x:20, y:2},
         {str:["C.","O.","OP"], x:19, y:6},
         {str:["K","I","E"], x:21, y:4}],

      grid: { str:
      [
         ".........OOOOO",
         ".......O.O....",
         ".......O.O....",
         "O.O.OOOOOOO...",
         "O.O..O.O......",
         "O.O..O.OOOOOO.",
         "O.O..O.O..O...",
         "O.O..O....O...",
         "OOOOOOOOO.O.O.",
         "O....O....O.O.",
         "O.....OOOOOOOO",
         "..........O.O.",
         "............O.",
         "............O."
      ], x:5, y:2},
      name: "SWEET TOOTH"
   },
   {
      pieces: [
         {str:["ZO"], x:5, y:14},
         {str:["VAM","..Y"], x:15, y:3},
         {str:["WE"], x:3, y:2},
         {str:["MB","U.","M."], x:18, y:7},
         {str:[".D","RE"], x:5, y:3},
         {str:["PI"], x:9, y:13},
         {str:["GH"], x:19, y:4},
         {str:["V.","IE","L."], x:1, y:3},
         {str:["WO"], x:19, y:2},
         {str:["RE"], x:1, y:11},
         {str:["OST",".K."], x:1, y:13},
         {str:[".T","GO",".N"], x:19, y:10},
         {str:["E.","LF","E."], x:1, y:7},
         {str:["BL"], x:3, y:6},
         {str:["W.","IN","T."], x:17, y:12},
         {str:["C","H"], x:15, y:5}],

      grid: { str:
      [
         "....OOOOO...",
         ".......O....",
         "....O..O....",
         ".OOOOOOOO...",
         "....O..O....",
         "OOOOOO.O..O.",
         "..O.O.OOOOOO",
         "..O....O..O.",
         "OOOOOOO...O.",
         "..O.......O."
      ], x:5, y:3},
      name: "MONSTER MASH"
   },
   {
      pieces: [
         {str:[".O.","PAN"], x:3, y:14},
         {str:[".E","WA",".L"], x:20, y:6},
         {str:["T.","MI"], x:1, y:9},
         {str:["OME"], x:1, y:12},
         {str:["FF"], x:5, y:3},
         {str:["CAK"], x:16, y:6},
         {str:["LK"], x:7, y:11},
         {str:["LES",".G."], x:16, y:8},
         {str:[".C","LE",".R"], x:7, y:13},
         {str:["GRI","S.."], x:1, y:2},
         {str:["ES","A.","L."], x:1, y:5},
         {str:["TS"], x:3, y:8},
         {str:[".T.","YOG"], x:19, y:14},
         {str:["A.","S.","TS"], x:16, y:13},
         {str:[".H","BA",".S"], x:20, y:10},
         {str:["URT",".O."], x:17, y:2},
         {str:["H","B"], x:1, y:14},
         {str:["W","N","S"], x:21, y:2},
         {str:["CON"], x:16, y:11}],

      grid: { str:
      [
         "......O........",
         "..OOOOOOO..O...",
         ".O....O...OOOOO",
         "OOOOOOOO...O...",
         ".O....O....O...",
         ".OOOO.O.O..O...",
         ".O.....OOOOOO..",
         "OOOOOOO.O..O...",
         ".O...O..O..O...",
         ".....OOOOO.O...",
         ".....O.....O..."
      ], x:4, y:3},
      name: "PART OF A COMPLETE BREAKFAST"
   },
   {
      pieces: [
         {str:["..C","HER"], x:1, y:4},
         {str:[".A",".N","PE"], x:20, y:2},
         {str:["..F","SPA"], x:19, y:14},
         {str:["DO",".N"], x:17, y:6},
         {str:["ON"], x:9, y:12},
         {str:["NG"], x:18, y:13},
         {str:["L","C"], x:14, y:12},
         {str:["RR"], x:1, y:7},
         {str:["VE"], x:20, y:6},
         {str:[".F",".L","CA"], x:17, y:2},
         {str:[".M.","UIN"], x:15, y:14},
         {str:["N.","G.","OW"], x:1, y:13},
         {str:["RDI"], x:4, y:15},
         {str:[".R.","PIG"], x:19, y:8},
         {str:["O.","ST","T."], x:1, y:9},
         {str:["C","H"], x:17, y:9},
         {str:[".P.","NAL"], x:3, y:11},
         {str:["R","R"], x:4, y:8},
         {str:["ORK","T.."], x:1, y:2},
         {str:["EON"], x:19, y:11}],

      grid: { str:
      [
         "..O...O.......",
         "OOOOO.O....O..",
         "..O..OOOOOOOO.",
         "..O...O....O..",
         ".OOOOOOO.O.O..",
         "......O..OOOOO",
         "...O..O..O.O..",
         ".OOOOOOO.O....",
         "...O....OOOOOO",
         "...O.....O....",
         "..OOOO...O....",
         "...O.........."
      ], x:4, y:3},
      name: "CROSS BIRD PUZZLE"
   },
   {
      pieces: [
         {str:["P","A"], x:2, y:13},
         {str:["CO","K."], x:19, y:8},
         {str:["SCH","..E"], x:18, y:3},
         {str:["F.","LO"], x:2, y:3},
         {str:["O","C","K"], x:2, y:9},
         {str:["R","D"], x:4, y:13},
         {str:["NY","E."], x:17, y:5},
         {str:["S","T"], x:16, y:13},
         {str:["OOL","..I"], x:2, y:6},
         {str:["RO",".A",".L"], x:4, y:9},
         {str:[".E.","PRI"], x:6, y:13},
         {str:["SWA","H.."], x:18, y:13},
         {str:["T","T"], x:5, y:3},
         {str:["OP"], x:19, y:11},
         {str:["M","U"], x:6, y:6},
         {str:["R.","DE"], x:8, y:6},
         {str:["E.","RM"], x:7, y:3}],

      grid: { str:
      [
         "..OOOOOO...",
         "....O..O...",
         "....O..O.O.",
         "....O..O.O.",
         "O......O.O.",
         "O.O...OOOOO",
         "OOOOOO...O.",
         "O.O.O.OOOOO",
         "..O.O.O....",
         "..O.OOOOO..",
         "......O....",
         "......O...."
      ], x:7, y:3},
      name: "A GROUP OF RHINOS IS CALLED A CRASH, YOU'RE WELCOME"
   }
];