var puzzles = [
  "V0FUQ0gsU1dJU1MsQkFOSyxURUxMRVIsRk9SVFVORQ%3D%3D",
  "Q1JPVyxST09LLEtOSUdIVCxCTEFDSyxXSURPVyxQRUFLLFNVTU1JVA",
  "TU9VTlRBSU5TLFJPQ0tZLFJPQUQsQ1JPU1MsQk9XLFJBSU4sU1RPUk0%3D",
  "TVVTSUNBTCxCRUFULEhFQVJULEFUVEFDSyxBU1NBVUxULEJBVFRFUlksQ0hBUkdFUg%3D%3D",
  "RElOTkVSLFJPTEwsUk9DSyxTVE9ORSxLSURORVksQkVBTixHUkVFTg%3D%3D",
  "RkxBRyxQT0xFLFBPU0lUSU9OLEpPQixHRU5FU0lTLEJJUlRILERFTElWRVJZ",
  "UEFMLE1BVEUsQ0hFQ0ssTUFSSyxTVEFJTg%3D%3D",
  "R1JVREdFLEJFRUYsQlVSR0VSLEtJTkcsQ1JPV04sSEVBRCxMRUFERVI%3D",
  "RkxPV0VSLEJVTEIsRkxBU0gsTElHSFQsSEVBVlk%3D",
  "Q0hBSU4sTUFJTCxMRVRURVIsU0NBUkxFVCxGRVZFUg%3D%3D",
  "REFURSxDT1VSVCxKVURHRSxHQVVHRSxNRVRFUixGT09ULEhBTkQ%3D",
  "VVAsRE9XTixQSUxMT1csQ1VTSElPTixTSElFTEQ%3D",
  "Q0xPQ0ssV0FUQ0gsVE9XRVIsTE9PTSxXRUFWRSxXRUIsSU5URVJORVQ%3D",
  "TUFUVFJFU1MsQkVELEdBUkRFTixTTFVHLEJVTExFVCxDQUxJQkVSLFFVQUxJVFk%3D",
  "U0tJVCxTS0VUQ0gsRFJBVyxCUklER0UsUE9LRVIsQ0hJUCxUT1JUSUxMQQ%3D%3D",
  "V0VCLE5FVCxHUk9TUyxGT1VMLFBFTkFMVFk%3D",
  "VFJFQVQsVFJJQ0ssRk9PTCxGTEFLRSxTTk9XLFdISVRFLEhPVVNF",
  "QlJBTkNILFNIT09ULEZJUkUsU01PS0UsUElQRSxXUkVOQ0gsVFdJU1Q%3D",
  "VFJBSU4sUFJBQ1RJQ0UsUkVIRVJTQUwsV0VERElORyxDQUtFLFdBTEssSkFZ",
  "R1JFRVRJTkcsQ0FSRCxERUNLLFNXQUIsQ09UVE9OLENBTkRZLENBTkU%3D"
];
  
function randomEncodedPuzzle() {
  return decodeURIComponent(puzzles[Math.floor(Math.random() * puzzles.length)]);
};

function getPuzzle(puzzle){
  return decodeURIComponent(puzzles[puzzle]);
};